# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2tROKS3vAc8qTrFz4N7PieVbRn-gSsO
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/MyDrive/Data AI4CKD.xlsx"
df = pd.read_excel(path)

df.head()

cols_to_drop = ["ID"]

# Colonnes post-diagnostic à exclure
cols_causes = [
    col for col in df.columns
    if col.startswith("Causes Majeure après Diagnostic/")
]

cols_to_drop.extend(cols_causes)

# Colonnes exclues
cols_to_drop = ["ID"]

cols_causes = [
    col for col in df.columns
    if col.startswith("Causes Majeure après Diagnostic/")
]

cols_to_drop.extend(cols_causes)

# Affichage
print("Variables exclues du dataset :\n")
for col in cols_to_drop:
    print("-", col)

df_final = df.drop(columns=cols_to_drop)

df_final['Stage de l\'IRC'].unique()

import pandas as pd

# Pourcentage de cellules non nulles par colonne
non_null_percentage = df_final.notnull().sum() / len(df_final) * 100

# Afficher les 10 premières colonnes pour vérifier
print(non_null_percentage.head)

non_null_percentage[non_null_percentage > 29]

import pandas as pd

# Calcul du pourcentage de cellules non nulles par colonne
non_null_percentage = df_final.notnull().sum() / len(df_final) * 100

# Sélection des colonnes avec plus de 50% de données présentes
selected_columns = non_null_percentage[non_null_percentage > 29].index

# Création d'un nouveau DataFrame avec ces colonnes
df_filtered = df_final[selected_columns]

# Colonnes à supprimer
columns_to_drop = [
    "Causes Majeure après Diagnostic/HTA",
    "Causes Majeure après Diagnostic/Diabète ID",
    "Nationalité"
]

# Suppression des colonnes si elles existent dans df_filtered
df_filtered = df_filtered.drop(columns=[col for col in columns_to_drop if col in df_filtered.columns])

import pandas as pd

# Détecter automatiquement les colonnes numériques et catégorielles
numeric_cols = df_filtered.select_dtypes(include=['number']).columns.tolist()
categorical_cols = df_filtered.select_dtypes(include=['object', 'category']).columns.tolist()

# Imputation pour les colonnes numériques (médiane)
for col in numeric_cols:
    df_filtered[col].fillna(df_filtered[col].median(), inplace=True)

# Imputation pour les colonnes catégorielles (mode)
for col in categorical_cols:
    df_filtered[col].fillna(df_filtered[col].mode()[0], inplace=True)

# Vérification des valeurs manquantes restantes
df_filtered.isnull().sum()

df_filtered.head(5)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ================================
# Étape 1 : Détection automatique des types
# ================================

# Target
target_col = "Stage de l'IRC"

# Colonnes numériques
numeric_cols = df_filtered.select_dtypes(include=['number']).columns.tolist()

# Retirer la target si elle est numérique
if target_col in numeric_cols:
    numeric_cols.remove(target_col)

# Détection des colonnes binaires (0/1)
binary_cols = [col for col in numeric_cols
               if df_filtered[col].nunique() == 2]

# Retirer les binaires des numériques continues
numeric_cols = [col for col in numeric_cols if col not in binary_cols]

# Colonnes catégorielles
categorical_cols = df_filtered.select_dtypes(include=['object', 'category']).columns.tolist()

# ================================
# Étape 2 : Analyse Univariée
# ================================

# -------- 2a) Variables numériques continues --------
print("\n=== Analyse Univariée : Variables Numériques ===")

for col in numeric_cols:
    print(f"\nColonne : {col}")
    print(df_filtered[col].describe())

    plt.figure(figsize=(6,3))
    sns.histplot(df_filtered[col], kde=True)
    plt.title(f'Distribution de {col}')
    plt.show()


# -------- 2b) Variables catégorielles --------
print("\n=== Analyse Univariée : Variables Catégorielles ===")

for col in categorical_cols:
    print(f"\nColonne : {col}")
    print(df_filtered[col].value_counts(dropna=False))

    plt.figure(figsize=(6,3))
    sns.countplot(y=col, data=df_filtered,
                  order=df_filtered[col].value_counts().index)
    plt.title(f'Distribution de {col}')
    plt.show()


# -------- 2c) Variables binaires (0/1) --------
print("\n=== Analyse Univariée : Variables Binaires (0/1) ===")

for col in binary_cols:
    print(f"\nColonne : {col}")
    print(df_filtered[col].value_counts())

    plt.figure(figsize=(4,2))
    sns.countplot(x=col, data=df_filtered)
    plt.title(f'Distribution de {col}')
    plt.show()


# -------- 2d) Target --------
print("\n=== Analyse Univariée : Target Stage de l'IRC ===")

print(df_filtered[target_col].value_counts())

plt.figure(figsize=(6,3))
sns.countplot(x=target_col, data=df_filtered)
plt.title("Distribution des stades de l'IRC")
plt.show()

# ================================
# LISTE FINALE DES FEATURES
# ================================

features = [

# 🔹 1. Démographiques
"Age",
"Sexe",
"Poids (Kg)",
"Taille (m)",

# 🔹 2. Signes vitaux
"TA (mmHg)/Systole",
"TA (mmHg)/Diastole",
"Poul (bpm)",
"Température (C°)",
"Conscience",
"Score de Glasgow (/15)",

# 🔹 3. Biologie sanguine
"Créatinine (mg/L)",
"Urée (g/L)",
"Na^+ (meq/L)",
"K^+ (meq/L)",
"Cl^- (meq/L)",
"Ca^2+ (meq/L)",
"P (meq/L)",
"Glycémie à jeun (taux de Glucose)",
"Cholestérol Total",
"Cholestérol HDL",
"Cholestérol LDL",
"Triglycérides",

# 🔹 4. Hématologie
"Hb (g/dL)",
"Hte (%)",
"VGM (fL)",
"TCMH (pg)",
"CCMH (%)",
"NB (G/L)",
"Plaquettes (g/L)",
"Anémie",

# 🔹 5. Urinaire
"Diurèse",
"Tests Populaires/PU (g/24h)",

# 🔹 6. Echographie
"Grosseur Rein Gauche ",
"Grosseur Rein Droit ",
"Différenciation des reins",
"Echogénicité",
"Contour régulier/Rein droit",
"Contour régulier/Rein gauche",
"Calcul Rénal",
"Kyste",

# 🔹 7. Comorbidités
"Personnels Médicaux/HTA",
"Personnels Médicaux/Diabète 2",
"Pathologies/Rétinopathie hypertensive",
"Pathologies/Rétinopathie diabétique"
]

# ================================
# TARGET
# ================================

target = "Stage de l'IRC"

# ================================
# EXTRACTION
# ================================

feat = df_filtered[features]
y = df_filtered[target]

print("Shape feat:", feat.shape)
print("Shape y :", y.shape)

feat

# ================================
# Affichage de la liste finale des features
# ================================

# feature_cols correspond aux colonnes utilisées pour X dans ton modèle
print("✅ Nombre total de features :", len(feat.columns))
print("✅ Liste finale des features :")
for i, col in enumerate(feat.columns, start=1):
    print(f"{i}. {col}")

# Afficher les 10 premières lignes du dataset X
import pandas as pd

pd.set_option('display.max_columns', None)  # Affiche toutes les colonnes
pd.set_option('display.max_rows', 50)       # Affiche jusqu'à 50 lignes (modifie selon besoin)

# Affichage
display(feat.head(50))  # Affiche les 50 premières lignes du dataset

import numpy as np
import pandas as pd

def calcul_dfg_ckd_epi(sexe, age, creatinine_mg_L):
    """
    Calcule le DFG selon la formule CKD-EPI 2021 (sans facteur ethnique).

    Paramètres :
    - sexe : 'F' ou 'M'
    - age : âge en années
    - creatinine_mg_L : créatinine en mg/L

    Retour :
    - DFG estimé en mL/min/1.73m² (arrondi à 2 décimales)
    """

    # Vérification des valeurs manquantes ou invalides
    if pd.isna(creatinine_mg_L) or pd.isna(age) or pd.isna(sexe):
        return np.nan
    if creatinine_mg_L <= 0 or age <= 0:
        return np.nan

    # Conversion mg/L → mg/dL
    creatinine_mg_dL = creatinine_mg_L / 10

    # Conversion sexe en string
    sexe_str = str(sexe).upper()

    # Paramètres selon le sexe
    if sexe_str == 'F':
        kappa = 0.7
        alpha = -0.241
        facteur_sexe = 1.012
    elif sexe_str == 'M':
        kappa = 0.9
        alpha = -0.302
        facteur_sexe = 1.0
    else:
        return np.nan  # sexe invalide

    # Formule CKD-EPI 2021
    dfg = (
        142
        * min(creatinine_mg_dL / kappa, 1) ** alpha
        * max(creatinine_mg_dL / kappa, 1) ** -1.200
        * (0.9938 ** age)
        * facteur_sexe
    )

    return round(dfg, 2)

df_filtered["dfg"] = df_filtered.apply(
    lambda row: calcul_dfg_ckd_epi(
        row["Sexe"],
        row["Age"],
        row["Créatinine (mg/L)"]
    ),
    axis=1
)

display(df_filtered[["Sexe", "Age", "Créatinine (mg/L)", "dfg"]].head(10))

# Retirer la ligne supplémentaire dans df_filtered
df_filtered_clean = df_filtered.loc[df_filtered.index.isin(feat.index)]

# Ajouter la colonne dfg à feat
feat["dfg"] = df_filtered_clean["dfg"].values

print("\nAperçu des 10 premières lignes de feat :")
display(feat.head(10))

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, LabelEncoder

# 🔹 Copier le dataset
df_ml = df_filtered.copy()

# ================================
# 1️⃣ CIBLE : Stage de l'IRC
# ================================

# Nettoyage
df_ml["Stage de l'IRC"] = df_ml["Stage de l'IRC"].astype(str).str.strip()

# Supprimer valeurs manquantes
df_ml = df_ml[df_ml["Stage de l'IRC"].notna()]

# 🚨 Supprimer la valeur "0" (classe invalide)
df_ml = df_ml[df_ml["Stage de l'IRC"] != "0"]

# Vérification avant encodage
print("Valeurs uniques AVANT encodage :")
print(df_ml["Stage de l'IRC"].unique())

# Encodage propre
le = LabelEncoder()
df_ml["Stage_de_l_IRC_Encoded"] = le.fit_transform(df_ml["Stage de l'IRC"])

# Vérification finale
print("\nEncodage des classes :")
for i, class_ in enumerate(le.classes_):
    print(f"{class_} --> {i}")

# ================================
# 2️⃣ VARIABLES BINAIRES
# ================================

binary_vars = [
    "Sexe",
    "Personnels Médicaux/HTA",
    "Personnels Médicaux/Diabète 2",
    "Pathologies/Rétinopathie hypertensive",
    "Pathologies/Rétinopathie diabétique",
    "Anémie",
    "Calcul Rénal",
    "Kyste",
    "Contour régulier/Rein droit",
    "Contour régulier/Rein gauche"
]

for col in binary_vars:
    df_ml[col + "_Encoded"] = df_ml[col].map({
        "Oui": 1, "Non": 0,
        "F": 1, "H": 0
    }).fillna(0)

# ================================
# 3️⃣ VARIABLES ORDINALES
# ================================

echogen_mapping = [
    "Normale", "Légère", "Modérée", "Sévère",
    "Normal", "Hyper Echogénicité", "Hypo Echogénicité"
]

df_ml["Echogénicité_Encoded"] = OrdinalEncoder(
    categories=[echogen_mapping],
    handle_unknown='use_encoded_value',
    unknown_value=-1
).fit_transform(df_ml[["Echogénicité"]])

diff_mapping = ["Conservée", "Diminuée", "Disparue"]

df_ml["Différenciation des reins_Encoded"] = OrdinalEncoder(
    categories=[diff_mapping],
    handle_unknown='use_encoded_value',
    unknown_value=-1
).fit_transform(df_ml[["Différenciation des reins"]])

df_ml["Score de Glasgow (/15)_Encoded"] = pd.to_numeric(
    df_ml["Score de Glasgow (/15)"], errors='coerce'
)

# ================================
# 4️⃣ VARIABLES LIPIDIQUES ET URINAIRES
# ================================

lipides_mapping = {"Réduit":0, "Normal":1, "Normale":1, "Augmenté":2}

for col in ["Cholestérol Total", "Cholestérol HDL",
            "Cholestérol LDL", "Triglycérides"]:
    df_ml[col + "_Encoded"] = df_ml[col].map(lipides_mapping)

diurese_mapping = {
    "Anurie":0,
    "Oligurie":1,
    "Non quantifiée":-1,
    "Préservée":2
}

df_ml["Diurèse_Encoded"] = df_ml["Diurèse"].map(diurese_mapping)

pu_mapping = {"-":0, "+":1}
df_ml["Tests Populaires/PU (g/24h)_Encoded"] = \
    df_ml["Tests Populaires/PU (g/24h)"].map(pu_mapping)

# ================================
# 5️⃣ VARIABLES NUMÉRIQUES
# ================================

numeric_vars = [
    "Age", "Poids (Kg)", "Taille (m)",
    "TA (mmHg)/Systole", "TA (mmHg)/Diastole",
    "Poul (bpm)", "Température (C°)",
    "Créatinine (mg/L)", "Urée (g/L)",
    "Glycémie à jeun (taux de Glucose)",
    "Hb (g/dL)", "Hte (%)",
    "Cholestérol Total_Encoded",
    "Cholestérol HDL_Encoded",
    "Cholestérol LDL_Encoded",
    "Triglycérides_Encoded",
    "Diurèse_Encoded",
    "Tests Populaires/PU (g/24h)_Encoded"
]

existing_numeric_vars = [col for col in numeric_vars if col in df_ml.columns]

scaler = StandardScaler()
df_ml[existing_numeric_vars] = scaler.fit_transform(
    df_ml[existing_numeric_vars]
)

# ================================
# 6️⃣ FEATURES & TARGET
# ================================

feature_cols = (
    [col + "_Encoded" for col in binary_vars] +
    ["Echogénicité_Encoded",
     "Différenciation des reins_Encoded",
     "Score de Glasgow (/15)_Encoded"] +
    existing_numeric_vars
)

X = df_ml[feature_cols]
y = df_ml["Stage_de_l_IRC_Encoded"]

print("\n✅ Shape X :", X.shape)
print("✅ Shape y :", y.shape)
print("✅ Colonnes utilisées :", X.columns.tolist())

X

# Retirer la ligne supplémentaire dans df_filtered
df_filtered_clean = df_filtered.loc[df_filtered.index.isin( X.index)]

# Ajouter la colonne dfg à X
X["dfg"] = df_filtered_clean["dfg"].values

print("\nAperçu des 10 premières lignes de X :")
display(X.head(10))

# Supprimer la classe qui a seulement 1 observation
y_counts = y.value_counts()

# Garder uniquement classes avec au moins 2 échantillons
valid_classes = y_counts[y_counts >= 2].index

mask = y.isin(valid_classes)

X = X[mask]
y = y[mask]

print("Nouvelle distribution :")
print(y.value_counts())

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score



# ===========================
# 2️⃣ Séparer Train / Test
# ===========================
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print(classification_report(y_test, y_pred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(xgb, X, y, cv=5, scoring='f1_macro')

print("F1 Macro CV :", scores)
print("Mean :", scores.mean())

import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))
plt.barh(X.columns, xgb.feature_importances_)
plt.show()

import xgboost
print(xgboost.__version__)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="mlogloss",
    early_stopping_rounds=20   # ✅ ici maintenant
)

xgb.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=False
)

print("Best iteration:", xgb.best_iteration)

# ==========================================
# 1️⃣ Importations
# ==========================================

import numpy as np
import matplotlib.pyplot as plt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay


# ==========================================
# 2️⃣ Séparation Train / Test
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)


# ==========================================
# 3️⃣ Modèle Final (96 arbres optimaux)
# ==========================================

xgb_final = XGBClassifier(
    n_estimators=96,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="mlogloss"
)

# Entraînement
xgb_final.fit(X_train, y_train)


# ==========================================
# 4️⃣ Prédictions
# ==========================================

y_pred = xgb_final.predict(X_test)


# ==========================================
# 5️⃣ Évaluation
# ==========================================

print("📊 Rapport de classification :\n")
print(classification_report(y_test, y_pred))

print("📊 Accuracy :", np.mean(y_pred == y_test))


# ==========================================
# 6️⃣ Matrice de confusion
# ==========================================

plt.figure(figsize=(8,6))
ConfusionMatrixDisplay.from_estimator(xgb_final, X_test, y_test)
plt.title("Matrice de Confusion - XGBoost Final")
plt.show()


# ==========================================
# 7️⃣ Feature Importance
# ==========================================

plt.figure(figsize=(10,8))
plt.barh(X.columns, xgb_final.feature_importances_)
plt.title("Feature Importance - XGBoost Final")
plt.xlabel("Importance")
plt.tight_layout()
plt.show()

import shap

# Explainer
explainer = shap.TreeExplainer(xgb_final)
shap_values = explainer.shap_values(X_test)

# Plot global importance
shap.summary_plot(shap_values, X_test)

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_test_bin = label_binarize(y_test, classes=np.unique(y))
y_score = xgb_final.predict_proba(X_test)

for i in range(y_test_bin.shape[1]):
    fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"Classe {i} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Multi-class")
plt.legend()
plt.show()

from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix

# ✅ Sélection des features importantes
important_features = [
    "dfg",
    "Créatinine (mg/L)",
    "Urée (g/L)",
    "Température (C°)",
    "Cholestérol LDL_Encoded",
    "Cholestérol Total_Encoded"
]

X_imp = df_ml[important_features]
y_imp = df_ml["Stage_de_l_IRC_Encoded"]

# ✅ Séparation train / test
X_train, X_test, y_train, y_test = train_test_split(
    X_imp, y_imp, test_size=0.2, random_state=42, stratify=y_imp
)

# ✅ Entraînement XGBoost
xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb.fit(X_train, y_train)

# ✅ Prédiction et évaluation
y_pred = xgb.predict(X_test)

print("🔹 Matrice de confusion :")
print(confusion_matrix(y_test, y_pred))

print("\n🔹 Rapport de classification :")
print(classification_report(y_test, y_pred))

# ✅ Feature importance pour ces 6 variables
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.barh(important_features, xgb.feature_importances_)
plt.title("Feature Importance - Variables clés uniquement")
plt.show()

import pickle

from xgboost import XGBClassifier
import pickle
import pandas as pd

# 🔹 1️⃣ Tes 6 features importantes
important_features = [
    "dfg",
    "Créatinine (mg/L)",
    "Urée (g/L)",
    "Température (C°)",
    "Cholestérol LDL_Encoded",
    "Cholestérol Total_Encoded"
]

X_imp = df_ml[important_features]  # DataFrame des features
y_imp = df_ml["Stage_de_l_IRC_Encoded"]  # Cible

# 🔹 2️⃣ Créer le modèle XGBoost avec les mêmes hyperparamètres
xgb_imp = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

# 🔹 3️⃣ Entraîner le modèle
xgb_imp.fit(X_imp, y_imp)

# 🔹 4️⃣ Sauvegarder le modèle strictement sur ces 6 features
filename = "xgb_model_6features.pkl"
with open(filename, "wb") as file:
    pickle.dump(xgb_imp, file)

print(f"✅ Modèle enregistré dans {filename} avec les 6 features")

# Charger le modèle
with open("xgb_model_6features.pkl", "rb") as file:
    xgb_loaded = pickle.load(file)

# Créer un DataFrame de test avec exactement les 6 features
X_test_new = pd.DataFrame([
    [60, 1.2, 0.5, 36.5, 1, 2],
    [45, 1.8, 0.7, 37.0, 2, 3],
    [70, 1.0, 0.4, 36.8, 1, 2]
], columns=important_features)

# Faire la prédiction
y_pred_new = xgb_loaded.predict(X_test_new)
print("✅ Prédictions :")
print(y_pred_new)

y_pred_new = [5, 5, 5]  # ✅ correct
print(y_pred_new)

from google.colab import files

# 🔹 Télécharger le fichier vers ton PC
files.download("xgb_model_6features.pkl")

